import type { Trip } from "./types";

export interface TripTemplate {
  slug: string;
  title: string;
  metaDescription: string;
  relatedBlogSlug: string;
  trip: Trip;
}

export const TRIP_TEMPLATES: TripTemplate[] = [
  {
    slug: "paris-honeymoon",
    title: "Paris Honeymoon Budget — 7 Days for 2",
    metaDescription:
      "Sample vacation budget for a 7-day Paris honeymoon for two. See a realistic expense breakdown by category including flights, hotels, dining, and activities.",
    relatedBlogSlug: "how-to-budget-a-vacation",
    trip: {
      id: "tpl-paris-honeymoon",
      name: "Paris Honeymoon",
      destination: "Paris, France",
      startDate: "2026-05-01",
      endDate: "2026-05-07",
      budget: 2800,
      baseCurrency: "USD",
      createdAt: "2026-01-15T00:00:00.000Z",
      updatedAt: "2026-01-15T00:00:00.000Z",
      travelers: [
        { id: "t1", name: "Alex" },
        { id: "t2", name: "Jordan" },
      ],
      expenses: [
        {
          id: "e1",
          tripId: "tpl-paris-honeymoon",
          description: "Round-trip flights (×2)",
          amount: 980,
          currency: "USD",
          category: "transport",
          date: "2026-05-01",
          paidBy: "t1",
          splitBetween: ["t1", "t2"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e2",
          tripId: "tpl-paris-honeymoon",
          description: "Hotel — Le Marais (7 nights)",
          amount: 840,
          currency: "USD",
          category: "accommodation",
          date: "2026-05-01",
          paidBy: "t2",
          splitBetween: ["t1", "t2"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e3",
          tripId: "tpl-paris-honeymoon",
          description: "Dining out (7 days)",
          amount: 420,
          currency: "USD",
          category: "food",
          date: "2026-05-01",
          paidBy: "t1",
          splitBetween: ["t1", "t2"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e4",
          tripId: "tpl-paris-honeymoon",
          description: "Louvre, Eiffel Tower, Seine cruise",
          amount: 280,
          currency: "USD",
          category: "activities",
          date: "2026-05-02",
          paidBy: "t2",
          splitBetween: ["t1", "t2"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e5",
          tripId: "tpl-paris-honeymoon",
          description: "Souvenirs & gifts",
          amount: 180,
          currency: "USD",
          category: "shopping",
          date: "2026-05-04",
          paidBy: "t1",
          splitBetween: ["t1", "t2"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e6",
          tripId: "tpl-paris-honeymoon",
          description: "Metro passes & local transport",
          amount: 100,
          currency: "USD",
          category: "transport",
          date: "2026-05-01",
          paidBy: "t2",
          splitBetween: ["t1", "t2"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
      ],
    },
  },
  {
    slug: "bali-backpacker",
    title: "Bali Backpacker Trip — 14 Days Solo",
    metaDescription:
      "Sample budget for a 14-day solo backpacking trip to Bali on $980. See daily costs for hostels, street food, scooter rental, and temples.",
    relatedBlogSlug: "offline-travel-apps",
    trip: {
      id: "tpl-bali-backpacker",
      name: "Bali Backpacker",
      destination: "Bali, Indonesia",
      startDate: "2026-06-01",
      endDate: "2026-06-14",
      budget: 980,
      baseCurrency: "USD",
      createdAt: "2026-01-15T00:00:00.000Z",
      updatedAt: "2026-01-15T00:00:00.000Z",
      travelers: [{ id: "t1", name: "Sam" }],
      expenses: [
        {
          id: "e1",
          tripId: "tpl-bali-backpacker",
          description: "Return flights",
          amount: 380,
          currency: "USD",
          category: "transport",
          date: "2026-06-01",
          paidBy: "t1",
          splitBetween: ["t1"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e2",
          tripId: "tpl-bali-backpacker",
          description: "Hostel dorms (14 nights ~$12/night)",
          amount: 168,
          currency: "USD",
          category: "accommodation",
          date: "2026-06-01",
          paidBy: "t1",
          splitBetween: ["t1"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e3",
          tripId: "tpl-bali-backpacker",
          description: "Street food & warung meals",
          amount: 210,
          currency: "USD",
          category: "food",
          date: "2026-06-01",
          paidBy: "t1",
          splitBetween: ["t1"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e4",
          tripId: "tpl-bali-backpacker",
          description: "Temples, rice terraces, surf lesson",
          amount: 120,
          currency: "USD",
          category: "activities",
          date: "2026-06-03",
          paidBy: "t1",
          splitBetween: ["t1"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e5",
          tripId: "tpl-bali-backpacker",
          description: "Scooter rental (14 days)",
          amount: 70,
          currency: "USD",
          category: "transport",
          date: "2026-06-01",
          paidBy: "t1",
          splitBetween: ["t1"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e6",
          tripId: "tpl-bali-backpacker",
          description: "Batik fabrics & local crafts",
          amount: 32,
          currency: "USD",
          category: "shopping",
          date: "2026-06-10",
          paidBy: "t1",
          splitBetween: ["t1"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
      ],
    },
  },
  {
    slug: "tokyo-group",
    title: "Tokyo Group Adventure — 10 Days for 4",
    metaDescription:
      "Sample vacation budget for a 10-day Tokyo trip with 4 friends totalling $6,000. Includes flights, Airbnb, ramen, day trips to Kyoto, and more.",
    relatedBlogSlug: "split-expenses-with-friends",
    trip: {
      id: "tpl-tokyo-group",
      name: "Tokyo Group Adventure",
      destination: "Tokyo, Japan",
      startDate: "2026-04-01",
      endDate: "2026-04-10",
      budget: 6000,
      baseCurrency: "USD",
      createdAt: "2026-01-15T00:00:00.000Z",
      updatedAt: "2026-01-15T00:00:00.000Z",
      travelers: [
        { id: "t1", name: "Alex" },
        { id: "t2", name: "Ben" },
        { id: "t3", name: "Caro" },
        { id: "t4", name: "Dana" },
      ],
      expenses: [
        {
          id: "e1",
          tripId: "tpl-tokyo-group",
          description: "Flights (×4)",
          amount: 2800,
          currency: "USD",
          category: "transport",
          date: "2026-04-01",
          paidBy: "t1",
          splitBetween: ["t1", "t2", "t3", "t4"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e2",
          tripId: "tpl-tokyo-group",
          description: "Airbnb apartment (10 nights)",
          amount: 1200,
          currency: "USD",
          category: "accommodation",
          date: "2026-04-01",
          paidBy: "t2",
          splitBetween: ["t1", "t2", "t3", "t4"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e3",
          tripId: "tpl-tokyo-group",
          description: "Food — ramen, sushi, izakayas",
          amount: 800,
          currency: "USD",
          category: "food",
          date: "2026-04-01",
          paidBy: "t3",
          splitBetween: ["t1", "t2", "t3", "t4"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e4",
          tripId: "tpl-tokyo-group",
          description: "JR Pass + local trains",
          amount: 480,
          currency: "USD",
          category: "transport",
          date: "2026-04-01",
          paidBy: "t4",
          splitBetween: ["t1", "t2", "t3", "t4"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e5",
          tripId: "tpl-tokyo-group",
          description: "TeamLab, Kyoto day trip, Nikko",
          amount: 400,
          currency: "USD",
          category: "activities",
          date: "2026-04-03",
          paidBy: "t1",
          splitBetween: ["t1", "t2", "t3", "t4"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e6",
          tripId: "tpl-tokyo-group",
          description: "Harajuku shopping & electronics",
          amount: 320,
          currency: "USD",
          category: "shopping",
          date: "2026-04-06",
          paidBy: "t2",
          splitBetween: ["t1", "t2", "t3", "t4"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
      ],
    },
  },
  {
    slug: "cancun-family",
    title: "Cancun Family Vacation — 7 Days for 4",
    metaDescription:
      "Sample family vacation budget for 7 days in Cancun for 2 adults and 2 kids. All-inclusive hotel, excursions, and spending money totalling $5,600.",
    relatedBlogSlug: "how-to-budget-a-vacation",
    trip: {
      id: "tpl-cancun-family",
      name: "Cancun Family Vacation",
      destination: "Cancun, Mexico",
      startDate: "2026-07-10",
      endDate: "2026-07-16",
      budget: 5600,
      baseCurrency: "USD",
      createdAt: "2026-01-15T00:00:00.000Z",
      updatedAt: "2026-01-15T00:00:00.000Z",
      travelers: [
        { id: "t1", name: "Parent 1" },
        { id: "t2", name: "Parent 2" },
        { id: "t3", name: "Kid 1" },
        { id: "t4", name: "Kid 2" },
      ],
      expenses: [
        {
          id: "e1",
          tripId: "tpl-cancun-family",
          description: "Flights (family of 4)",
          amount: 1600,
          currency: "USD",
          category: "transport",
          date: "2026-07-10",
          paidBy: "t1",
          splitBetween: ["t1", "t2"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e2",
          tripId: "tpl-cancun-family",
          description: "All-inclusive resort (7 nights)",
          amount: 2800,
          currency: "USD",
          category: "accommodation",
          date: "2026-07-10",
          paidBy: "t2",
          splitBetween: ["t1", "t2"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e3",
          tripId: "tpl-cancun-family",
          description: "Chichen Itza day trip",
          amount: 320,
          currency: "USD",
          category: "activities",
          date: "2026-07-12",
          paidBy: "t1",
          splitBetween: ["t1", "t2"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e4",
          tripId: "tpl-cancun-family",
          description: "Water park & snorkeling",
          amount: 280,
          currency: "USD",
          category: "activities",
          date: "2026-07-13",
          paidBy: "t2",
          splitBetween: ["t1", "t2"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e5",
          tripId: "tpl-cancun-family",
          description: "Dining outside resort",
          amount: 360,
          currency: "USD",
          category: "food",
          date: "2026-07-11",
          paidBy: "t1",
          splitBetween: ["t1", "t2"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e6",
          tripId: "tpl-cancun-family",
          description: "Souvenirs & gifts",
          amount: 240,
          currency: "USD",
          category: "shopping",
          date: "2026-07-15",
          paidBy: "t2",
          splitBetween: ["t1", "t2"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
      ],
    },
  },
  {
    slug: "barcelona-weekend",
    title: "Barcelona Weekend Getaway — 4 Days for 2",
    metaDescription:
      "Sample budget for a 4-day Barcelona weekend trip for a couple at $1,040. Flights, a central hotel, tapas, Sagrada Família, and nightlife.",
    relatedBlogSlug: "how-to-budget-a-vacation",
    trip: {
      id: "tpl-barcelona-weekend",
      name: "Barcelona Weekend",
      destination: "Barcelona, Spain",
      startDate: "2026-09-04",
      endDate: "2026-09-07",
      budget: 1040,
      baseCurrency: "USD",
      createdAt: "2026-01-15T00:00:00.000Z",
      updatedAt: "2026-01-15T00:00:00.000Z",
      travelers: [
        { id: "t1", name: "Riley" },
        { id: "t2", name: "Morgan" },
      ],
      expenses: [
        {
          id: "e1",
          tripId: "tpl-barcelona-weekend",
          description: "Flights (×2)",
          amount: 360,
          currency: "USD",
          category: "transport",
          date: "2026-09-04",
          paidBy: "t1",
          splitBetween: ["t1", "t2"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e2",
          tripId: "tpl-barcelona-weekend",
          description: "Boutique hotel — Eixample (4 nights)",
          amount: 360,
          currency: "USD",
          category: "accommodation",
          date: "2026-09-04",
          paidBy: "t2",
          splitBetween: ["t1", "t2"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e3",
          tripId: "tpl-barcelona-weekend",
          description: "Tapas, vermouth, seafood paella",
          amount: 160,
          currency: "USD",
          category: "food",
          date: "2026-09-04",
          paidBy: "t1",
          splitBetween: ["t1", "t2"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e4",
          tripId: "tpl-barcelona-weekend",
          description: "Sagrada Família & Park Güell",
          amount: 80,
          currency: "USD",
          category: "activities",
          date: "2026-09-05",
          paidBy: "t2",
          splitBetween: ["t1", "t2"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e5",
          tripId: "tpl-barcelona-weekend",
          description: "Metro & taxi",
          amount: 40,
          currency: "USD",
          category: "transport",
          date: "2026-09-04",
          paidBy: "t1",
          splitBetween: ["t1", "t2"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e6",
          tripId: "tpl-barcelona-weekend",
          description: "Nightlife & cocktail bars",
          amount: 40,
          currency: "USD",
          category: "entertainment",
          date: "2026-09-05",
          paidBy: "t2",
          splitBetween: ["t1", "t2"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
      ],
    },
  },
  {
    slug: "prague-stag",
    title: "Prague Stag/Bachelor Trip — 5 Days for 6",
    metaDescription:
      "Sample budget for a 5-day Prague stag/bachelor trip for 6 people totalling $2,700. Hostel, beer, river cruise, and group activities.",
    relatedBlogSlug: "split-expenses-with-friends",
    trip: {
      id: "tpl-prague-stag",
      name: "Prague Stag Trip",
      destination: "Prague, Czech Republic",
      startDate: "2026-08-14",
      endDate: "2026-08-18",
      budget: 2700,
      baseCurrency: "USD",
      createdAt: "2026-01-15T00:00:00.000Z",
      updatedAt: "2026-01-15T00:00:00.000Z",
      travelers: [
        { id: "t1", name: "Jake" },
        { id: "t2", name: "Tom" },
        { id: "t3", name: "Mike" },
        { id: "t4", name: "Dan" },
        { id: "t5", name: "Chris" },
        { id: "t6", name: "Ryan" },
      ],
      expenses: [
        {
          id: "e1",
          tripId: "tpl-prague-stag",
          description: "Flights (×6)",
          amount: 1080,
          currency: "USD",
          category: "transport",
          date: "2026-08-14",
          paidBy: "t1",
          splitBetween: ["t1", "t2", "t3", "t4", "t5", "t6"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e2",
          tripId: "tpl-prague-stag",
          description: "Party hostel — Old Town (5 nights)",
          amount: 540,
          currency: "USD",
          category: "accommodation",
          date: "2026-08-14",
          paidBy: "t2",
          splitBetween: ["t1", "t2", "t3", "t4", "t5", "t6"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e3",
          tripId: "tpl-prague-stag",
          description: "Food & beer (5 days)",
          amount: 600,
          currency: "USD",
          category: "food",
          date: "2026-08-14",
          paidBy: "t3",
          splitBetween: ["t1", "t2", "t3", "t4", "t5", "t6"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e4",
          tripId: "tpl-prague-stag",
          description: "River cruise & escape room",
          amount: 300,
          currency: "USD",
          category: "activities",
          date: "2026-08-15",
          paidBy: "t4",
          splitBetween: ["t1", "t2", "t3", "t4", "t5", "t6"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
        {
          id: "e5",
          tripId: "tpl-prague-stag",
          description: "Nightlife & clubs",
          amount: 180,
          currency: "USD",
          category: "entertainment",
          date: "2026-08-15",
          paidBy: "t5",
          splitBetween: ["t1", "t2", "t3", "t4", "t5", "t6"],
          createdAt: "2026-01-15T00:00:00.000Z",
        },
      ],
    },
  },
];
